//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseList
    {
        public int ID { get; set; }
        public string CourseCode { get; set; }
        public string CourceName { get; set; }
        public Nullable<double> CreditHour { get; set; }
        public Nullable<double> ContactHour { get; set; }
    }
}
