//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentProjectEntities : DbContext
    {
        public StudentProjectEntities()
            : base("name=StudentProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentInformation> StudentInformations { get; set; }
        public virtual DbSet<CourseList> CourseLists { get; set; }
        public virtual DbSet<vwStudentList> vwStudentLists { get; set; }
        public virtual DbSet<StudentCourse> StudentCourses { get; set; }
        public virtual DbSet<vwStudentInformation> vwStudentInformations { get; set; }
    }
}
