//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStudentInformation
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string ContactNo { get; set; }
        public string MailingAddress { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherContactNo { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherContactNo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
